### ISSUE TITLE
Roll requests not being sent to players

### ISSUE THREAD

**Issue by AtreidesGhola** [seanmccarty/RequestedRolls#42]
Choosing a character and clicking the requested roll was not sending the request to the players. 

Using the drop down ms at the bottom of the app window and clicking the dice button still sends the roll.

**Comment by seanmccarty** [comment]
Once I click the button that enables this feature, it works flawlessly for me. I can't imagine how any other extensions would conflict with this, but it is possible. Please let me know if the reinstall works. Otherwise, we will need to start going through steps for replication, which would need things like which roll type (e.g. save or check, and acrobatics, etc...) are you trying to send, is the player connected, what are the other settings you have on.

**Comment by AtreidesGhola** [comment]
I think you can close this.  I reinstalled the extension, and it seems to be working now.  
For future reference, it was exhibiting this behavior on every roll type.
